include/evse_security.hpp
include/evse_utilities.hpp
include/x509_bundle.hpp
include/x509_wrapper.hpp
lib/evse_security.cpp
lib/x509_bundle.cpp
lib/x509_wrapper.cpp
tests/tests.cpp

- install certificate check if already contained
- last valid certificate retrieval move in bundle helper
- added certificate directory helper
- added support for the case when the V2G root doesn't contain the full chain

Update for v2g module interoperability:

---

include/evse_security.hpp
include/sec_types.hpp
lib/evse_security.cpp

This implements file signature validation as used for OCPP firmware updates (maybe the function naming could reflect that). There's already some error handling, but there might be more cases I've overlooked, would be glad for some feedback here.

Added file signature validation

---

lib/evse_security/evse_security.cpp

Fixed for bundle directory usage:
- certificate retrieval for directories (get_verify_file)
- certificate install status (is_ca_certificate_installed)

Fixed an issue with certificate directory support

---

include/evse_security/evse_security.hpp
include/evse_security/evse_types.hpp
lib/evse_security/evse_security.cpp

* Support updating of certificate links
* Adjust `get_key_pair` to return both single leaf and chain (if found)

Add support for certificate links

---

include/evse_security/certificate/x509_bundle.hpp
include/evse_security/certificate/x509_wrapper.hpp
include/evse_security/evse_security.hpp
lib/evse_security/certificate/x509_bundle.cpp
lib/evse_security/evse_security.cpp
tests/CMakeLists.txt
tests/tests.cpp

- maximum used filesize limit
- maximum certificate entries
- deletion of expired csr private keys
- deletion of unmanaged csr in case of a reboot
- safety limits for deleting only the oldest leafs and keeping a minimum of 10
- checks so that leaf directories don't overlap in any way bundle directories
- relevant test cases

Added cleanup/certificate limit features:

---

README.md
include/evse_security/crypto/interface/crypto_types.hpp
lib/evse_security/CMakeLists.txt
lib/evse_security/crypto/openssl/openssl_supplier.cpp
lib/evse_security/evse_security.cpp
tests/openssl_supplier_test.cpp
tests/openssl_supplier_test_tpm.cpp
tests/tests.cpp

I'm using the client certificate as a TLS server certificate for MQTT and need to include the required subject alternative name fields in the certificate signing request (CSR).
i.e. subject alternative name can be added with DNS name and/or IPv4 address
By default the subject alternative name extension is not added to the CSR. When CSR_DNS_NAME or CSR_IP_ADDRESS are set using cmake then a subject alternative name extension is created and populated with the supplied values,
e.g.
```
cmake -DCSR_DNS_NAME=install.pionix.de
```
APIs and methods could be updated to enable run-time configuration

Build time configuration for CSR

---

lib/evse_security/crypto/openssl/openssl_supplier.cpp

- Removex -x509_strict flag, when checking if a child is issued by or child of another certificate, always caused issues for different older certificates and made hierarchy build only partial

Removed strict cert verification, added error string print

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/pull_request_template.md

* Added issue and PR templates
* Added CODEOWNERS file

 Add issue and PR templates and CODEOWNERS file

---

include/evse_security/evse_types.hpp
lib/evse_security/certificate/x509_bundle.cpp
lib/evse_security/certificate/x509_hierarchy.cpp
lib/evse_security/certificate/x509_wrapper.cpp
lib/evse_security/evse_security.cpp
lib/evse_security/evse_types.cpp

A instance of using the wrong certificate hash have been fixed. The OCSP cache now builds the certificate hierarchy and retrieves the certificate hash later. A crash has been so prevented.
Naming the certificate leafs have been made clearer, from "SECC_LEAF" to "CSMS_LEAF" or "MF_LEAF" based on the LeafCertificateType.

Fixed some potentially wrong uses of certificate hash

---

include/evse_security/crypto/interface/crypto_supplier.hpp
include/evse_security/crypto/interface/crypto_types.hpp
include/evse_security/crypto/openssl/openssl_supplier.hpp
include/evse_security/evse_security.hpp
include/evse_security/evse_types.hpp
lib/evse_security/crypto/interface/crypto_supplier.cpp
lib/evse_security/crypto/openssl/openssl_supplier.cpp
lib/evse_security/evse_security.cpp
tests/openssl_supplier_test.cpp
tests/tests.cpp

- Refactor `verify_certificate` so that it can also be used to validate a P&C contract certificate chain
- Add generation of OCSP request data
https://github.com/EVerest/libocpp/issues/324

Mg refactor verify certificate

---

CMakeLists.txt
include/evse_security/evse_security.hpp
lib/evse_security/evse_security.cpp
lib/evse_security/evse_types.cpp

* now two functions to get OCSP request data exist: get_v2g_ocsp_request_data and get_ocsp_request_data
* implemented both functions according to requirements of Plug&Charge
* added LeafCertificate::MO to conversions

Split OCSP data requests into two separate functions

---

include/evse_security/evse_security.hpp
lib/evse_security/crypto/openssl/openssl_supplier.cpp
lib/evse_security/evse_security.cpp

Add extra 'IssuerNotFound' error

---

.github/workflows/build_and_test.yaml
include/evse_security/evse_types.hpp
lib/evse_security/crypto/openssl/openssl_tpm.cpp
tests/tests.cpp

- Bump version of used github action run-clang-format to v1.1.0
https://github.com/EVerest/everest-ci/issues/11

Bump version of used github action run-clang-format to v1.1.0

---

include/evse_security/crypto/interface/crypto_supplier.hpp
include/evse_security/crypto/openssl/openssl_supplier.hpp
include/evse_security/detail/openssl/openssl_types.hpp
lib/evse_security/crypto/interface/crypto_supplier.cpp
lib/evse_security/crypto/openssl/openssl_supplier.cpp
lib/evse_security/evse_security.cpp
tests/openssl_supplier_test.cpp

There was an issue during certificate verification, that presumed that intermediary certificates presented during either a leaf update or on a car certificate validation were trusted, which is not the case. The function 'x509_verify_certificate_chain' has been updated to reflect the correct functionality.

When veryfing a certificate the intermediary subcas

---

lib/evse_security/evse_security.cpp

Added a missing return statement for clarity purposes. Added another early return statement if we do not find any chain/single leaf certificates.

Fixed a missing return statement

---

include/evse_security/detail/openssl/openssl_types.hpp
lib/evse_security/crypto/openssl/openssl_supplier.cpp

Previously X509HandleOpenSSL and KeyHandleOpenSSL were defined in openssl_supplier.cpp this made it difficult to create Handles from other OpenSSL code and use the methods in evse-security.

feat: expose OpenSSL handles so that other code can create objects

---

lib/evse_security/evse_security.cpp

The code exceptions when there OCSP cache directory doesn't exist.
This fix catches the exception so that an error can be logged rather than terminating EVerest
example error prior to fix:
```
2024-06-17 10:48:57.318956 [INFO] evse_security:E  :: Found valid leaf: ["/home/james/code/everest/workspace/everest-core/build/dist/etc/everest/certs/client/cso/CPO_CERT_CHAIN.pem"]
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
what():  filesystem error: directory iterator cannot open directory: No such file or directory [/home/james/code/everest/workspace/everest-core/build/dist/etc/everest/certs/client/cso/ocsp]
2024-06-17 10:48:57.652987 [CRIT] manager         int boot(const boost::program_options::variables_map&) :: Module evse_security (pid: 59760) …
```

fix: catch directory not found when iterating over OCSP cache

---

CMakeLists.txt
include/evse_security/crypto/openssl/openssl_crypto_supplier.hpp
include/evse_security/crypto/openssl/openssl_types.hpp
lib/evse_security/CMakeLists.txt
lib/evse_security/crypto/openssl/openssl_crypto_supplier.cpp

Detail header, made public for various usage across other modules that might require part of libevse functionality.

Removed openssl types from detail headers

---

lib/evse_security/evse_security.cpp

In the following PR we are not presuming that the response to a CSR by the CSMS contains the leaf + SUBCAs but it will only output the single leaf, and will output the leaf+chain only if the received list is > than 1

Modified code not to presume that a multi-chain certificate is always returned

---

README.md
include/evse_security/certificate/x509_hierarchy.hpp
include/evse_security/evse_security.hpp
include/evse_security/evse_types.hpp
lib/evse_security/certificate/x509_hierarchy.cpp
lib/evse_security/evse_security.cpp
tests/CMakeLists.txt
tests/configs/seccLeafCert_Alternate.cnf
tests/configs/v2gRootCACert_Alternate.cnf
tests/generate_test_certs.sh
tests/generate_test_certs_multi.sh
tests/tests.cpp

Introduces one API call that allows the retrieval of the retrieval of multiple leaf certificate chains, that are linked to different roots. 
Core related branch: https://github.com/EVerest/everest-core/tree/feature/multi_root_trusted_ca

Multiple root trusted CA leafs

---

3rd_party/cert_rehash/c_rehash.hpp
CMakeLists.txt
include/evse_security/evse_security.hpp
lib/evse_security/CMakeLists.txt
lib/evse_security/evse_security.cpp
tests/tests.cpp

Support hashing a certificate directory

---

include/evse_security/certificate/x509_wrapper.hpp
include/evse_security/evse_types.hpp
lib/evse_security/CMakeLists.txt
lib/evse_security/certificate/x509_bundle.cpp
lib/evse_security/certificate/x509_wrapper.cpp
lib/evse_security/evse_security.cpp
tests/CMakeLists.txt
tests/tests.cpp

- Added extra information for debug build for easy hierarchy inspection
- Fixed certificate return order for V2GCertificateChain from Leaf->Sec1->Sec2 to Leaf->Sec2->Sec1
Closes: https://github.com/EVerest/libevse-security/issues/102

Fixed bug in return certificate order for V2GChertificateChain

---

CMakeLists.txt
include/evse_security/evse_security.hpp
lib/evse_security/evse_security.cpp
tests/tests.cpp

Added new function to the API that allows to provide multiple certificate_types / trust anchors when a certificate is verified.
This is particularly useful for verifying contract certificates for Plug&Charge, since those shall use V2G and MO root certificates as trust anchors.

Certificate Verification: Multiple trust anchors
